### ISSUE TITLE
Results meaning

### ISSUE THREAD

**Issue by StasyaPion** [nemesida-waf/waf-bypass#10]
Hi guys, I'm curious what is BYPASSED, PASSED etc. means in the results of the program? Can you provide a little description, please? I'm a little confused about how to interpret the results... 

For the **False Negative** test: 
1) Does the PASSED means "Not vulnerable"? Does it mean that payloads in this column didn't triggered WAF Bypass and WAF successfully blocked the malicious request? 
2) Does the BYPASSED means "Vulnerable"? Does it mean that payloads in this column triggered WAF Bypass and WAF failed to block the malicious requests? 
3) FAILED is about Failed requests? (e.g.,cannot connect to server, incorrect response code etc.) I found it in your code, but can you confirm that? 

For the **False Positive** test: 
1) Does the PASSED means "Not vulnerable"? Does it mean that payloads in this column didn't triggered WAF Bypass and WAF successfully blocked the malicious request? 
2) Does the FALSED means that WAF blocks the Legitimate requests and that's why it's "Vulnerable"? 

By the way, your program is awesome, thanks <3

**Comment by Romanov-R** [comment]
Thanks for your feedback!

So,
- PASSED meaning "OK"
- FALSED (False Positive) meaning "Blocked, but should be blocked"
- BYPASSED (False Negative) meaning "Not blocked, but should be blocked"
- FAILED (ERROR) - meaning "Request could not be processed, e.g. connection error, incorrect response from the WebServer/WAF etc."
