### ISSUE TITLE
Test run failed

### ISSUE THREAD

**Issue by JianfuYang** [nemesida-waf/waf-bypass#14]
![image](https://github.com/nemesida-waf/waf-bypass/assets/48349252/fcc34c2d-837f-4ad4-83c9-9350fb7745b8)
Run the script according to the tutorial, and report this error directly. Has any brother Jimei encountered this error? How did you solve it?

**Comment by JianfuYang** [comment]
使用docker运行，不管哪个域（测试）都是这样？有大佬能正常跑通的吗？

**Comment by JianfuYang** [comment]
![企业微信截图_1687168282356](https://github.com/nemesida-waf/waf-bypass/assets/48349252/11dc6feb-e843-4d93-b727-a99aedeacdfa)
求指导

**Comment by Romanov-R** [comment]
Sorry, could you explain your issue in English?

**Comment by JianfuYang** [comment]
> 

This is the problem I encountered, thank you for your attention and answer

**Comment by Romanov-R** [comment]
> ![image](https://user-images.githubusercontent.com/48349252/246794548-fcc34c2d-837f-4ad4-83c9-9350fb7745b8.png) Run the script according to the tutorial, and report this error directly. Has any brother Jimei encountered this error? How did you solve it?

I can't to reproduce this error, please, provide more information, how I can reproduce it, including OS and ver.
