### ISSUE TITLE
Hard to identify and replay individual failures?

### ISSUE THREAD

**Issue by dankegel** [nemesida-waf/waf-bypass#18]
After using waf-bypass, often one wants to zero in on individual failures and replay them, but it seems hard to do.

waf-bypass could make this easier in many ways.

For instance, it could output curl commands (a la https://github.com/ofw/curlify) or a json equivalent (a la https://curlconverter.com/json) for each failure case to a log file.
Alternately, it could provide a --replay option that accepts an identifier from log file and replays just that one request.

**Comment by Romanov-R** [comment]
Thanks for your recommendation, cURL commend output has been added with commit c73fff8d1580781aee998c5d3972c72898ca6bc8
