### ISSUE TITLE
Suggestion: Adding some sort of progress output

### ISSUE THREAD

**Issue by nrathaus** [nemesida-waf/waf-bypass#21]
At the moment the product doesn't provide any progress, there is no way to know if you are 10% through, 50% through or 99% through

The output given to the user is either nothing (if there are no unexpected outcome) or very noisy (if there is a lot of unexpected outcome)

Since the code knows how many file (json) payloads there are, the product can know where it is ... at one progress it is ... Also it can provide some sort of ETA based on previous progress

If you wish I can develop this and offer a PR for it

**Comment by nrathaus** [comment]
Relevant code area: `all_files_list`

This variable knows what payloads we have

**Comment by nrathaus** [comment]
Note the best solution, but it works:
```
completed_list = {}

def progress_result(all_files_list):
    """"""
    start_time = datetime.datetime.now()
    while True:
        total = len(all_files_list)
        left = len(all_files_list) - len(completed_list.keys())
        elapsed = datetime.datetime.now() - start_time
        time_left = 0
        if total - left > 0:
            time_left = elapsed.seconds / (total - left) * left
        if left <= 0:
            print("done")
            break

        print(f"{left}/{total} {(1 - left/total) * 100.0:.2f}%, eta: {time_left:.2f}s")
        time.sleep(1)
```
```
        background_progress = threading.Thread(target=progress_result, args=[all_files_list])
        background_progress.start()
        pool = ThreadPool(processes=self.threads)
        pool.map(send_payload, all_files_list)
```
```
        def send_payload(json_path):
            try:
                # init
                completed_list[json_path] = 1
```

**Comment by contentgap** [comment]
would you love  to please show me how the tool actually works please...like the details

**Comment by nrathaus** [comment]
@contentgap I am bit confused, your response is related to my suggestion? or in general about the tool? if it is in general about the tool - its best to open a new issue

**Comment by Romanov-R** [comment]
> At the moment the product doesn't provide any progress, there is no way to know if you are 10% through, 50% through or 99% through
> 
> The output given to the user is either nothing (if there are no unexpected outcome) or very noisy (if there is a lot of unexpected outcome)
> 
> Since the code knows how many file (json) payloads there are, the product can know where it is ... at one progress it is ... Also it can provide some sort of ETA based on previous progress
> 
> If you wish I can develop this and offer a PR for it

Thanks for your efforts to make the tool more convenient to use. We implemented the progress bar with ETA (https://github.com/nemesida-waf/waf-bypass/commit/1fd6b5a5c388656548d14c1a9dd457bda6ec9421)
