### ISSUE TITLE
Good script but few confusion

### ISSUE THREAD

**Issue by Vincentssssssss** [nemesida-waf/waf-bypass#22]
It s a great script and enables me to evaluate the current waf capability, could you plz clarify below

1. how do we understand bypass and failed, bypass means it s successfully injected an attack against the waf?
2. with regards to payload in each output, how can we understand more details about this sample. etc XSS22.
3. where to check the details output ?

![image](https://github.com/user-attachments/assets/c83c82ab-24ce-4ba4-9a8f-9bd9e7c23ea3)

**Comment by Romanov-R** [comment]
Bypass means that your WAF bypass an attack
Failed means that your WAF have some issue/error while processing the request (e.g. WAF does not response the request etc.), in normal mode you can see failed request on the top as yellow string
To check details use '--details' option
