### ISSUE TITLE
NewConnectionError on all payloads (100% fail rate)

### ISSUE THREAD

**Issue by PinkyAlexCS** [nemesida-waf/waf-bypass#23]
Hello,

Seems to be a really interesting tool though I couldn't make it work.
Not with python, nor with docker image.

I'm getting following errors on all test cases (with 100% failed):
An error occurred while processing payload XSS/134.json in REFERER: WBHTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92f83d9e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
I'm attaching scan results.
<img width="1814" alt="Scan results" src="https://github.com/user-attachments/assets/62598dd4-d24e-4ead-a1f3-20fb5b01e546">

The site is available on 127.0.0.1 and other WAF test tools (e.g. identyWaf, WhatWaf) were able to reach it.

Kind regards,
Alex.

P.S.:
It would be nice to reword headings. For new user they feel confusing PASS/FAIL/BYPASS especially considering false-positive and false-negative context. I understand it's using QA naming (PASS/FAIL) but it may not be obvious for people who are not familiar with testing.
Can I propose something like this?
False-negative: BLOCKED (or similar that indicates that attack was prevented, instead of PASSED) | BYPASSED |  TEST CASES FAILED (or TESTING FAILED).
False-positive: PASSED | FALSELY BLOCKED (instead of FALSED) | TEST CASES FAILED.

Thank you for this cool tool!
It looks really interesting.

**Comment by Romanov-R** [comment]
Pls, create the new topic in discussion (https://github.com/nemesida-waf/waf-bypass/discussions)

**Comment by PinkyAlexCS** [comment]
I think this is the reason in bypass.py:
result = s.request(method, self.host, headers=headers, proxies=self.proxy, timeout=self.timeout, verify=False)

It looks like request doesn't set port.

I'm not a Python developer but following change resolved the issue:
if method.upper() == "GET":
                result = requests.get("http://127.0.0.1:8080", headers=headers, proxies=self.proxy, timeout=self.timeout, verify=False)
            elif method.upper() == "POST":
                result = requests.post("http://127.0.0.1:8080", headers=headers, proxies=self.proxy, timeout=self.timeout, verify=False)

**Comment by PinkyAlexCS** [comment]
You were right about creating discussion.
It seems to be my environment issue. Without any changes it started working today.
There are still some fails but they are marginal comparing to overall number of tests.

![image](https://github.com/user-attachments/assets/231ae5f7-1fbd-4ed7-b12b-a04f8f0d58c8)


Thank you for this cool tool!
