### ISSUE TITLE
Not getting failed payloads on using --curl-replay, getting only bypassed payloads

### ISSUE THREAD

**Issue by Utkarsh2104** [nemesida-waf/waf-bypass#25]
I want to check the curl request for the failed cases but on using --curl-replay, its showing only for bypassed cases and not for failed cases.

**Comment by Romanov-R** [comment]
No way, the cURL string generated on request's response:

<code>
result = s.request(method, host, headers=headers, proxies=self.proxy, timeout=self.timeout, verify=False)
curl = curlify.to_curl(result.request).replace('\r\n', '\\r\\n')
</code>

For some failed requests there is no answer, only an exception, and it is not possible to generate cURL request to reproduce.
