### ISSUE TITLE
mistake in number union 

### ISSUE THREAD

**Issue by Mhdy333p** [nemesida-waf/waf-bypass#8]
https://github.com/nemesida-waf/waf-bypass/blob/ea9d8eef669abf1e03173b41588a99d84beed123/payload/SQLi/1.json#L4

' or /*!u%6eion*/ /*!se%6cect*/ 1,2,3,4,5,6,7,8,9,0,11 '--

**Comment by Romanov-R** [comment]
Thanks, fixed
